import { createLoopbackServer } from "../extensions/loop-execution-visualizer/src/server.mjs";
const s = createLoopbackServer({ handlers: {}, log: () => {} });
const t = s.issueBootstrap();
console.log("token:", t, "len", t.length);
console.log("redeem same:", JSON.stringify(s.redeemBootstrap(t)));
console.log("redeem again:", JSON.stringify(s.redeemBootstrap(t)));
console.log("redeem bogus:", JSON.stringify(s.redeemBootstrap("nope")));
const t2 = s.issueBootstrap();
const t3 = s.issueBootstrap();
console.log("after 2 more issues, redeem t2:", JSON.stringify(s.redeemBootstrap(t2)));
console.log("redeem t3:", JSON.stringify(s.redeemBootstrap(t3)));
